#!/usr/bin/env python3
"""Generate the Codex plugin manifests from the Claude Code ones.

Codex and Claude Code turn out to be close cousins: both use `SKILL.md` with
`name` + `description` frontmatter, both have a plugin manifest and a
marketplace manifest, and both accept the same `PreToolUse` deny payload. What
differs is only where the files live and what they are called.

So the Claude manifests are the single source of truth and these are derived.
Two manifests hand-maintained in parallel is exactly how `marketplace.json` sat
at 5.4.1 for ten releases while everything else moved on.

  .claude-plugin/plugin.json       →  .codex-plugin/plugin.json
  .claude-plugin/marketplace.json  →  .agents/plugins/marketplace.json

`--check` verifies they are current without writing, for CI.

Exit codes:
  0 — written, or already current under --check
  1 — --check found drift
  2 — I/O error
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

CLAUDE_PLUGIN = ROOT / ".claude-plugin" / "plugin.json"
CLAUDE_MARKET = ROOT / ".claude-plugin" / "marketplace.json"
CODEX_PLUGIN = ROOT / ".codex-plugin" / "plugin.json"
CODEX_MARKET = ROOT / ".agents" / "plugins" / "marketplace.json"

GENERATED_NOTE = (
    "Generated by scripts/checks/sync-codex-manifests.py from .claude-plugin/. "
    "Do not edit by hand; edit the Claude manifest and re-run."
)


def build_codex_plugin(claude: dict) -> dict:
    """Codex plugin.json. `skills` points at the same directory Claude Code
    scans, so one skills tree serves both."""
    return {
        "_generated": GENERATED_NOTE,
        "name": claude["name"],
        "version": claude["version"],
        "description": claude.get("description", ""),
        "author": claude.get("author", {}),
        "homepage": claude.get("homepage", "https://github.com/kbichave/skills"),
        "license": claude.get("license", "MIT"),
        "keywords": claude.get("keywords", []),
        "skills": "./skills/",
        "interface": {"displayName": "Deep"},
    }


def build_codex_marketplace(claude_market: dict, plugin: dict) -> dict:
    """Codex marketplace.json. Note the nested `source` object and the
    `policy` block, neither of which Claude Code uses."""
    return {
        "_generated": GENERATED_NOTE,
        "name": claude_market["name"],
        "interface": {
            "displayName": claude_market.get("name", "kbichave-skills"),
            "description": claude_market.get("description", ""),
        },
        "plugins": [
            {
                "name": plugin["name"],
                "source": {"source": "local", "path": "./"},
                "policy": {"installation": "AVAILABLE"},
                "category": "Developer Tools",
            }
        ],
    }


def render(data: dict) -> str:
    return json.dumps(data, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files are current; write nothing",
    )
    args = parser.parse_args()

    try:
        claude_plugin = json.loads(CLAUDE_PLUGIN.read_text())
        claude_market = json.loads(CLAUDE_MARKET.read_text())
    except (OSError, ValueError) as exc:
        print(json.dumps({"error": f"cannot read Claude manifests: {exc}"}), file=sys.stderr)
        return 2

    targets = {
        CODEX_PLUGIN: render(build_codex_plugin(claude_plugin)),
        CODEX_MARKET: render(
            build_codex_marketplace(claude_market, claude_plugin)
        ),
    }

    stale: list[str] = []
    for path, content in targets.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if args.check:
        print(
            json.dumps(
                {
                    "current": not stale,
                    "stale": stale,
                    "fix": "uv run scripts/checks/sync-codex-manifests.py",
                },
                indent=2,
            )
        )
        return 1 if stale else 0

    print(json.dumps({"written": stale or "already current"}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
